# Generated by Django 5.1.4 on 2025-01-11 16:18

from django.db import migrations


def populate_initial_data(apps, schema_editor):
    # 1. Get models dynamically (or just import them)
    Unit = apps.get_model('GamifiedFittness', 'Unit')
    Activity = apps.get_model('GamifiedFittness', 'Activity')
    Challenge = apps.get_model('GamifiedFittness', 'Challenge')
    Badge = apps.get_model('GamifiedFittness', 'Badge')

    # 2. Fill units
    units = [
        {"id":1, "name": "minutes"},
        {"id":2, "name": "repetitions"},
        {"id":3, "name": "kilometers"},
    ]
    for unit in units:
        Unit.objects.get_or_create(**unit)

    # 3. Fill activities
    activities = [
        {"id":1, "name": "Running", "unit": Unit.objects.get(name="kilometers"), "points": 20, "calories": 100},
        {"id":2, "name": "Push-ups", "unit": Unit.objects.get(name="repetitions"), "points": 0.5, "calories": 1.2},
        {"id":3, "name": "Cycling", "unit": Unit.objects.get(name="minutes"), "points": 1.5, "calories": 6.0},
        {"id":4, "name": "Walking", "unit": Unit.objects.get(name="minutes"), "points": 1.0, "calories": 3.5},
    ]
    for activity in activities:
        Activity.objects.get_or_create(**activity)

    # 4. Fill challenges
    challenges = [
        {"id":1, "name": "30 Day Running Challenge", "description": "Run every day for 30 days", "points": 100, "calories": 1000, "start_date": "2025-01-01", "end_date": "2025-01-30", "slug": "30_Day_Running_Challenge"},
        { "id":2, "name": "Push-up Challenge", "description": "Complete 200 push-ups in a week", "points": 50, "calories": 250, "start_date": "2025-01-01", "end_date": "2025-01-07", "slug": "Push_up_Challenge"},
    ]
    for challenge in challenges:
        Challenge.objects.get_or_create(**challenge)

    # 5. Fill badges
    badges = [
        {"id":1, "name": "First Activity", "description": "Completed first activity", "criteria": "Complete any activity."},
        {"id":2, "name": "Runner", "description": "Ran 100 kilometers", "criteria": "Complete 100 kilometers of running."},
        {"id":3, "name": "Workout Master", "description": "Completed 500 repetitions", "criteria": "Complete 500 repetitions in workouts."},
    ]
    for badge in badges:
        Badge.objects.get_or_create(**badge)



class Migration(migrations.Migration):

    dependencies = [
        ('GamifiedFittness', '0001_initial')
    ]

    operations = [
        migrations.RunPython(populate_initial_data),
    ]
