# Generated by Django 5.1.4 on 2025-01-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamifiedFittness', '0002_auto_20250111_1956'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
    ]
