# Generated by Django 5.1.4 on 2025-01-15 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamifiedFittness', '0003_alter_userbadge_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='UserChallengeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='GamifiedFittness.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserChallengeReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('ChallengeComment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='GamifiedFittness.userchallengecomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
