# Generated by Django 5.1.4 on 2025-01-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamifiedFittness', '0006_alter_challenge_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='participants',
        ),
    ]
